export default {
  AnimationEvent: [],
  AudioProcessingEvent: [],
  BeforeInputEvent: [],
  BeforeUnloadEvent: [],
  BlobEvent: [],
  ClipboardEvent: [],
  CloseEvent: [],
  CompositionEvent: [],
  CSSFontFaceLoadEvent: [],
  CustomEvent: [],
  DeviceLightEvent: [],
  DeviceMotionEvent: [],
  DeviceOrientationEvent: [],
  DeviceProximityEvent: [],
  DOMTransactionEvent: [],
  DragEvent: ['drag', 'dragstart', 'dragenter', 'dragover', 'dragend', 'drop', 'dragleave'],
  EditingBeforeInputEvent: [],
  ErrorEvent: [],
  FetchEvent: [],
  FocusEvent: [],
  GamepadEvent: [],
  HashChangeEvent: [],
  IDBVersionChangeEvent: [],
  InputEvent: ['input'],
  KeyboardEvent: ['keydown', 'keyup', 'keypress'],
  MediaStreamEvent: [],
  MessageEvent: [],
  MouseEvent: ['click', 'mousedown', 'mouseup', 'mouseover', 'mousemove', 'mouseout', 'mouseenter', 'mouseleave'],
  MutationEvent: [],
  OfflineAudioCompletionEvent: [],
  PageTransitionEvent: [],
  PointerEvent: [],
  PopStateEvent: [],
  ProgressEvent: [],
  RelatedEvent: [],
  RTCDataChannelEvent: [],
  RTCIdentityErrorEvent: [],
  RTCIdentityEvent: [],
  RTCPeerConnectionIceEvent: [],
  SensorEvent: [],
  StorageEvent: [],
  SVGEvent: [],
  SVGZoomEvent: [],
  TimeEvent: [],
  TouchEvent: [],
  TrackEvent: [],
  TransitionEvent: [],
  UIEvent: [],
  UserProximityEvent: [],
  WebGLContextEvent: [],
  WheelEvent: []
};
